/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.clemlaf.conlost;

import android.support.v4.app.FragmentActivity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import org.clemlaf.conlost.MonitorService;

public class ConlostActivity extends FragmentActivity
{
  @Override
  public void onCreate(Bundle savedInstanceState)
  {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.main);
    startService();
  }
  private void startService() {
    final Context c = getApplicationContext();
    final Intent i = new Intent(c, MonitorService.class);
    c.startService(i);
  }
    public void quitService(View v){
	final Context c = getApplicationContext();
        final Intent i = new Intent(c, MonitorService.class);
	c.stopService(i);
	finish();
    }
}

